# EDRN Portal Imaging
# ===================
#
# This workflow builds and registers an image of the "Renaissance" of P5, the Early Detection Research
# Network's public portal.

---

name: P5 Imaging


# Triggers
# --------
#
# Run on any push to main or release branches of the P5 code.

on:
    push:
        branches:
            -   main
            -   release/*
        paths:
            -   'src/**'
            -   'docker/Dockerfile'


# Jobs
# ----
#
# What to do.

jobs:
    imaging:
        name: üèû P5 Imaging
        runs-on: ubuntu-latest
        steps:
            -
                name: üí≥ Docker Hub Identification
                uses: docker/login-action@v3
                with:
                    username: ${{secrets.DOCKERHUB_USERNAME}}
                    password: ${{secrets.DOCKERHUB_TOKEN}}
            -
                name: üìö Repository Checkout
                uses: actions/checkout@v6
            -
                name: üêç Python Wrangling
                uses: actions/setup-python@v6
                with:
                    python-version: '3.13'
            -
                name: ‚ò∏Ô∏è Wheel Generation
                run: |
                    python -m pip install --quiet --upgrade pip setuptools wheel build
                    for pkg in src/*; do
                        python -m build --outdir dist $pkg
                    done
            -
                name: üé∞ QEMU Multiple Machine Emulation
                uses: docker/setup-qemu-action@v3
            -
                name: üö¢ Docker Buildx
                uses: docker/setup-buildx-action@v3
            -
                name: üß± Image Construction and Publication ‚Äî user ID 500
                uses: docker/build-push-action@v6
                with:
                    build-args: user_id=500
                    context: .
                    file: docker/Dockerfile
                    platforms: linux/amd64,linux/arm64
                    push: true
                    tags: |
                        ${{secrets.DOCKERHUB_USERNAME}}/edrn-portal:latest
                        ${{secrets.DOCKERHUB_USERNAME}}/edrn-portal:latest-uid500
            -
                name: üß± Image Construction and Publication ‚Äî user ID 26013
                uses: docker/build-push-action@v6
                with:
                    build-args: user_id=26013
                    context: .
                    file: docker/Dockerfile
                    platforms: linux/amd64,linux/arm64
                    push: true
                    tags: |
                        ${{secrets.DOCKERHUB_USERNAME}}/edrn-portal:latest-uid26013

...

# FYI, as of 2022-01-25, the possible `platforms` that QEMU provides to the `platforms` of the image construction
# step are the following:
#
#   linux/amd64,linux/arm64,linux/riscv64,linux/ppc64le,linux/s390x,linux/386,linux/mips64le,
#   linux/mips64,linux/arm/v7,linux/arm/v6

# -*- mode: YAML; tab-width: 4 -*-
